### ISSUE TITLE
order of concatenated sequences

### ISSUE THREAD

**Issue by aldertzomer** [nylander/catfasta2phyml#1]
Hi,
I've used your tool in the past, it's very useful. The old version concatenated the fasta files exactly as they were listed on the command line. The new version however does not do that. Is that intended or a bug?
best wishes
Aldert

**Comment by nylander** [comment]
Dear Aldert,
It seems to be a "feature" ;-) 
The reason is due to the use of a hash data structure which doesn't keep the order. I might find the time to include a sorting function to make sure the input order is kept. I would agree that this would be a desirable feature. As a reminder, when conveniently using wild card expansions (e.g. `*.fas`) for input, files are sorted (most often) alphabetically.
/Johan
